### ISSUE TITLE
webpack4-react少了src文件夹

### ISSUE THREAD

**Issue by guiyujie** [HeavenSky/webpack-frames#1]
webpack4-react少了src文件夹
按readme.md操作会报错.

**Comment by HeavenSky** [comment]
不好意思，webpack4-*里面我都没有拷贝src文件夹,都可以从对应的webpack3-*里面拷贝一份,
比如 拷贝  webpack3-react/src  到   webpack4-react/src
比如 拷贝  webpack3-vue/src  到   webpack4-vue/src

另外这些在根目录的readme有说明,    webpack4-react里面忘记加了
