### ISSUE TITLE
webpack1-ie8 项目, 在IE8下面报错

### ISSUE THREAD

**Issue by webliving** [HeavenSky/webpack-frames#3]
如下图:

![image](https://user-images.githubusercontent.com/3808577/56127923-d7becf80-5fb0-11e9-8412-5f76560007e8.png)

**Comment by HeavenSky** [comment]
回头我找个windows试试，看你的截图，你用的是xp吗？ 这个现在好少见。
我用了快两年mac，已经回不去windows了，你这个问题你看看首页的readme重要说明，能不能解决，不能的话建议你改用https://github.com/HeavenSky/react-antd-ie8

**Comment by HeavenSky** [comment]
> 如下图:
> 
> ![image](https://user-images.githubusercontent.com/3808577/56127923-d7becf80-5fb0-11e9-8412-5f76560007e8.png)

问题已经修复，有空你自己再看看吧

**Comment by HeavenSky** [comment]
今天刚刚在朋友台式机上测试了的，另外做了如果报错，将错误日志打印在命令行，便于查看错误，在ie上实在不便于查看错误
