### ISSUE TITLE
webpack1-ie8 对象不支持“startsWith”属性或方法

### ISSUE THREAD

**Issue by johnlin0207** [HeavenSky/webpack-frames#7]
npm i 后ie11会报这个错, ie8下缺少标识符(eval的)

**Comment by HeavenSky** [comment]
开发坏境启动
npm start
需要支持 ie 时请用
npm run env -- FOR_IE=1 npm start
浏览器打开 http://localhost:8888
生产坏境部署
npm run app
需要支持 ie 时请用
npm run env -- FOR_IE=1 npm run app
拷贝 dist 文件夹内容至服务器即可

**Comment by HeavenSky** [comment]
麻烦先看readme

**Comment by johnlin0207** [comment]
> 开发坏境启动
> npm start
> 需要支持
> ，即时请用npm run env-FOR_IE = 1 npm start
> 浏览器打开[http：// localhost：8888](http://localhost:8888)
> 生产坏境部署
> npm run app
> 需要支持，即时请用
> npm run env- FOR_IE = 1 npm run appcopy
> dist文件夹内容至服务器即可

暂时不在ie8折腾wenpack了, XD

**Comment by miaozilong** [comment]
还是一样的问题
使用了npm run env -- FOR_IE=1 npm run app也不行
把config中的FOR_IE强制改成true也不行

IE11和IE8都不支持.

**Comment by miaozilong** [comment]
都报错
